let teams = [
    {
        "team_id": 1,
        "team_name_full": "Atlanta Hawks",
        "city_name": "Atlanta",
        "team_name": "Hawks",
    },
    {
        "team_id": 2,
        "team_name_full": "Boston Celtics",
        "city_name": "Boston",
        "team_name": "Celtics",
    },
    {
        "team_id": 3,
        "team_name_full": "Brooklyn Nets",
        "city_name": "Brooklyn",
        "team_name": "Nets",
    },
    {
        "team_id": 4,
        "team_name_full": "Charlotte Hornets",
        "city_name": "Charlotte",
        "team_name": "Hornets",
    },
    {
        "team_id": 5,
        "team_name_full": "Chicago Bulls",
        "city_name": "Chicago",
        "team_name": "Bulls",
    {
        "team_id": 6,
        "team_name_full": "Cleveland Cavaliers",
        "city_name": "Cleveland",
        "team_name": "Cavaliers",
    },
    {
        "team_id": 7,
        "team_name_full": "Dallas Mavericks",
        "city_name": "Dallas",
        "team_name": "Mavericks",
    },
    {
        "team_id": 8,
        "team_name_full": "Denver Nuggets",
        "city_name": "Denver",
        "team_name": "Nuggets",
    },
    {
        "team_id": 9,
        "team_name_full": "Detroit Pistons",
        "city_name": "Detroit",
        "team_name": "Pistons",
    },
    {
        "team_id": 10,
        "team_name_full": "Golden State Warriors",
        "city_name": "Golden State",
        "team_name": "Golden State Warriors",
    },
    {
        "team_id": 11,
        "team_name_full": "Houston Rockets",
        "city_name": "Houston",
        "team_name": "Rockets",
    },
    {
        "team_id": 12,
        "team_name_full": "Indiana Pacers",
        "city_name": "Indiana",
        "team_name": "Pacers",
    },
    {
        "team_id": 13,
        "team_name_full": "LA Clippers",
        "city_name": "LA",
        "team_name": "Clippers",
    },
    {
        "team_id": 14,
        "team_name_full": "Los Angeles Lakers",
        "city_name": "Los Angeles",
        "team_name": "Lakers",
    },
    {
        "team_id": 15,
        "team_name_full": "Memphis Grizzlies",
        "city_name": "Memphis",
        "team_name": "Grizzlies",
    },
    {
        "team_id": 16,
        "team_name_full": "Miami Heat",
        "city_name": "Miami",
        "team_name": "Heat",
    },
    {
        "team_id": 17,
        "team_name_full": "Milwaukee Bucks",
        "city_name": "Milwaukee",
        "team_name": "Bucks",
    },
    {
        "team_id": 18,
        "team_name_full": "Minnesota Timberwolves",
        "city_name": "Minnesota",
        "team_name": "Timberwolves",
    },
    {
        "team_id": 19,
        "team_name_full": "New Orleans Pelicans",
        "city_name": "New Orleans",
        "team_name": "Pelicans",
    },
    {
        "team_id": 20,
        "team_name_full": "New York Knicks",
        "city_name": "New York",
        "team_name": "Knicks",
    },
    {
        "team_id": 21,
        "team_name_full": "Oklahoma City Thunder",
        "city_name": "Oklahoma City",
        "team_name": "Thunder",
    },
    {
        "team_id": 22,
        "team_name_full": "Orlando Magic",
        "city_name": "Orlando",
        "team_name": "Magic",
    },
    {
        "team_id": 23,
        "team_name_full": "Philadelphia 76ers",
        "city_name": "Philadelphia",
        "team_name": "76ers",
    },
    {
        "team_id": 24,
        "team_name_full": "Phoenix Suns",
        "city_name": "Phoenix",
        "team_name": "Suns",
    },
    {
        "team_id": 25,
        "team_name_full": "Portland Trail Blazers",
        "city_name": "Portland",
        "team_name": "Trail Blazers",
    },
    {
        "team_id": 26,
        "team_name_full": "Sacramento Kings",
        "city_name": "Sacramento",
        "team_name": "Kings",
    },
    {  
        "team_id": 27,
        "team_name_full": "San Antonio Spurs",
        "city_name": "San Antonio",
        "team_name": "Spurs",
    },
    {
        "team_id": 28,
        "team_name_full": "Toronto Raptors",
        "city_name": "Toronto",
        "team_name": "Raptors",
    },
    {
        "team_id": 29,
        "team_name_full": "Utah Jazz",
        "city_name": "Utah",
        "team_name": "Jazz",
    },
    {
        "team_id": 30,
        "team_name_full": "Washington Wizards",
        "city_name": "Washington",
        "team_name": "Wizards",
    
    },
]